# Generated by Django 3.2.3 on 2021-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploaderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='types',
            field=models.IntegerField(choices=[(3, 'enterprise'), (2, 'premium'), (1, 'basic')], default=0),
        ),
    ]
