# Generated by Django 3.2.3 on 2021-05-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploaderApp', '0003_auto_20210514_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='types',
            field=models.IntegerField(choices=[(3, 'enterprise'), (1, 'basic'), (2, 'premium')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_links', to='ImageUploaderApp.image'),
        ),
    ]
