# Generated by Django 3.2.3 on 2021-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploaderApp', '0004_auto_20210514_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='types',
            field=models.IntegerField(choices=[(2, 'premium'), (1, 'basic'), (3, 'enterprise')], default=0),
        ),
    ]
