# Generated by Django 3.2.3 on 2021-05-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploaderApp', '0005_alter_accounttype_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='images',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='types',
            field=models.IntegerField(choices=[(1, 'basic'), (3, 'enterprise'), (2, 'premium')], default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ImageUploaderApp.user'),
        ),
    ]
