# Generated by Django 3.2.3 on 2021-05-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploaderApp', '0006_auto_20210514_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='types',
            field=models.IntegerField(choices=[(3, 'enterprise'), (2, 'premium'), (1, 'basic')], default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_links', to='ImageUploaderApp.user'),
        ),
    ]
