# Generated by Django 3.2.3 on 2021-05-16 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploaderApp', '0007_auto_20210514_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
